### ISSUE TITLE
KeyError: Caught KeyError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by vishwa15-lab** [sbelharbi/Deep-Ordinal-Classification-with-Inequality-Constraints#1]
================================================================================
                                  START TRAINING
================================================================================
 0%|                                                    | 0/80 [00:00<?, ?it/s]
['~/Deep-Ordinal-Classification-with-Inequality-Constraints/cmds/FGNET/images/035A07.JPG', '7']
['~/Deep-Ordinal-Classification-with-Inequality-Constraints/cmds/FGNET/images/058A03.JPG', '3']
['~/Deep-Ordinal-Classification-with-Inequality-Constraints/cmds/FGNET/images/058A05.JPG', '5']
['~/Deep-Ordinal-Classification-with-Inequality-Constraints/cmds/FGNET/images/003A38.JPG', '38']
['~/Deep-Ordinal-Classification-with-Inequality-Constraints/cmds/FGNET/images/055A08.JPG', '8']
['~/Deep-Ordinal-Classification-with-Inequality-Constraints/cmds/FGNET/images/010A04.JPG', '4']
Traceback (most recent call last):
  File "main.py", line 333, in <module>
    training_log, ALLOW_MULTIGPUS=ALLOW_MULTIGPUS, NBRGPUS=NBRGPUS)
  File "/home/vishwa/Deep-Ordinal-Classification-with-Inequality-Constraints/deeplearning/train.py", line 48, in train_one_epoch
    enumerate(dataloader), ncols=80, total=length):
  File "/home/vishwa/anaconda3/envs/env_souf/lib/python3.7/site-packages/tqdm/_tqdm.py", line 897, in __iter__
    for obj in iterable:
  File "/home/vishwa/anaconda3/envs/env_souf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/vishwa/anaconda3/envs/env_souf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/vishwa/anaconda3/envs/env_souf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/vishwa/anaconda3/envs/env_souf/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/vishwa/anaconda3/envs/env_souf/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/vishwa/anaconda3/envs/env_souf/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/vishwa/anaconda3/envs/env_souf/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/vishwa/Deep-Ordinal-Classification-with-Inequality-Constraints/loader.py", line 634, in __getitem__
    img, mask, target = self.load_sample_i(index)
  File "/home/vishwa/Deep-Ordinal-Classification-with-Inequality-Constraints/loader.py", line 464, in load_sample_i
    label = self.get_original_input_label_int(i)
  File "/home/vishwa/Deep-Ordinal-Classification-with-Inequality-Constraints/loader.py", line 450, in get_original_input_label_int
    return self.name_classes[label_str]
KeyError: 16

**Comment by sbelharbi** [comment]
the code seems to work properly.

i cloned this repo.
installed the requirements.
run the code for multiple datasets with no error.

make sure you installed properly the requirements, downloaded the datasets,
and set this functions properly to indicate the path to your data: tools.get_rootpath_2_dataset(). i clarified this better in the readme.

i re-uploaded the same requirements file i used for my test.
the previous one contains three unnecessary lines and an unnecessary package.

also, from your log, it seems you have modified the code ... not sure where the initial lines come from
` ['/Deep-Ordinal-Classification-with-Inequality-Constraints/cmds/FGNET/images/035A07.JPG', '7']`...

closing this issue.
thanks

'''sh
python main.py --cudaid 1 --yaml fgnet.yaml

================================================================================
                         ACTIVATE_SYNC_BN WAS SET TO TRUE
================================================================================


================================================================================
 SYNCHRONIZED BN HAS BEEN DEACTIVATED.
MULTIGPU MODE HAS BEEN DEACTIVATED. 2 GPUS
================================================================================

===============================================================
In Bash, you need to create an environment variable of the seed named `MYSEED`, then set its value to an integer.
For example, to create an environment named `MYSEED` and set it to the value 0, in your Bash terminal, before running this script, type: `export MYSEED=0`.
 .... [NOT OK]
github-test/Deep-Ordinal-Classification-with-Inequality-Constraints/reproducibility.py:37: UserWarning: WE ARE GOING TO USE OUR DEFAULT SEED: 0  .... [NOT OK]
  " {}  .... [NOT OK]".format(DEFAULT_SEED))
===============================================================
                DEFAULT SEED: 0  
===============================================================
strict: None  -----> True

================================================================================
                                SPLIT: 0 	 FOLD: 0
================================================================================


================================================================================
                         CREATING DATASETS AND DATALOADERS
================================================================================

Downloading: "http://sceneparsing.csail.mit.edu/model/pretrained_resnet/resnet18-imagenet.pth" to ./pretrained/resnet18-imagenet.pth
`ResNet(): deep module.` was successfully instantiated. Nbr.params: 11504542 .... [OK]
Optimizer `['dampening:0.0', 'lr:0.001', "lr_scheduler:{'gamma': 0.1, 'last_epoch': -1, 'min_lr': 1e-07, 'name': 'mystep', 'step_size': 40}", 'momentum:0.9', 'name:sgd', 'nesterov:True', 'weight_decay:1e-05']` was successfully instantiated .... [OK]
Learning scheduler `['gamma:0.1', 'last_epoch:-1', 'min_lr:1e-07', 'name:mystep', 'step_size:40']` was successfully instantiated .... [OK]

================================================================================
                                  START TRAINING
================================================================================

100%|███████████████████████████████████████████| 80/80 [00:08<00:00, 11.86it/s]
Tr.Ep  0: ACC: 0.0469, MAE: 12.0688, SOI_Y: 0.5122, SOI_PY: 0.5302, Loss: 4.0028, LR: ['1.00e-03'], t: 0.0000, time:0:00:08.322251
100%|█████████████████████████████████████████| 170/170 [00:04<00:00, 47.57it/s]
Vl.Ep  0: ACC: 0.0529, MAE: 14.6412, SOI_Y: 0.5012, SOI_PY: 0.5171, Loss: 3.9359, t:0.0000, time:0:00:04.520292
Plotting stats ...
100%|███████████████████████████████████████████| 80/80 [00:07<00:00, 12.13it/s]
Tr.Ep  1: ACC: 0.0906, MAE: 10.5859, SOI_Y: 0.5153, SOI_PY: 0.5329, Loss: 3.5632, LR: ['1.00e-03'], t: 0.0000, time:0:00:07.715251
100%|█████████████████████████████████████████| 170/170 [00:04<00:00, 39.41it/s]
Vl.Ep  1: ACC: 0.0706, MAE: 9.5647, SOI_Y: 0.5194, SOI_PY: 0.5390, Loss: 3.7650, t:0.0000, time:0:00:04.661714
Plotting stats ...
 62%|██████████████████████████▉                | 50/80 [00:04<00:02, 11.32it/s]^C

'''


'''sh
python main.py --cudaid 1 --yaml afad-lite.yaml

================================================================================
                        ACTIVATE_SYNC_BN WAS SET TO TRUE
================================================================================


================================================================================
SYNCHRONIZED BN HAS BEEN DEACTIVATED.
MULTIGPU MODE HAS BEEN DEACTIVATED. 2 GPUS
================================================================================

===============================================================
In Bash, you need to create an environment variable of the seed named `MYSEED`, then set its value to an integer.
For example, to create an environment named `MYSEED` and set it to the value 0, in your Bash terminal, before running this script, type: `export MYSEED=0`.
.... [NOT OK]
github-test/Deep-Ordinal-Classification-with-Inequality-Constraints/reproducibility.py:37: UserWarning: WE ARE GOING TO USE OUR DEFAULT SEED: 0  .... [NOT OK]
 " {}  .... [NOT OK]".format(DEFAULT_SEED))
===============================================================
               DEFAULT SEED: 0  
===============================================================
strict: None  -----> True

================================================================================
                               SPLIT: 0 	 FOLD: 0
================================================================================


================================================================================
                        CREATING DATASETS AND DATALOADERS
================================================================================

`ResNet(): deep module.` was successfully instantiated. Nbr.params: 11381422 .... [OK]
Optimizer `['dampening:0.0', 'lr:0.001', "lr_scheduler:{'gamma': 0.1, 'last_epoch': -1, 'min_lr': 1e-07, 'name': 'mystep', 'step_size': 40}", 'momentum:0.9', 'name:sgd', 'nesterov:True', 'weight_decay:1e-05']` was successfully instantiated .... [OK]
Learning scheduler `['gamma:0.1', 'last_epoch:-1', 'min_lr:1e-07', 'name:mystep', 'step_size:40']` was successfully instantiated .... [OK]

================================================================================
                                 START TRAINING
================================================================================

100%|███████████████████████████████████████| 4752/4752 [07:08<00:00, 11.10it/s]
Tr.Ep  0: ACC: 0.0986, MAE: 4.8597, SOI_Y: 0.5762, SOI_PY: 0.6582, Loss: 2.8585, LR: ['1.00e-03'], t: 0.0000, time:0:07:08.438823
 4%|█▍                                      | 342/9479 [00:08<04:17, 35.49it/s]^C


'''

'''sh
python main.py --cudaid 1 --yaml historical-color-image-decade.yaml

================================================================================
                         ACTIVATE_SYNC_BN WAS SET TO TRUE
================================================================================


================================================================================
 SYNCHRONIZED BN HAS BEEN DEACTIVATED.
MULTIGPU MODE HAS BEEN DEACTIVATED. 2 GPUS
================================================================================

===============================================================
In Bash, you need to create an environment variable of the seed named `MYSEED`, then set its value to an integer.
For example, to create an environment named `MYSEED` and set it to the value 0, in your Bash terminal, before running this script, type: `export MYSEED=0`.
 .... [NOT OK]
github-test/Deep-Ordinal-Classification-with-Inequality-Constraints/reproducibility.py:37: UserWarning: WE ARE GOING TO USE OUR DEFAULT SEED: 0  .... [NOT OK]
  " {}  .... [NOT OK]".format(DEFAULT_SEED))
===============================================================
                DEFAULT SEED: 0  
===============================================================
strict: None  -----> True

================================================================================
                                SPLIT: 0 	 FOLD: 0
================================================================================


================================================================================
                         CREATING DATASETS AND DATALOADERS
================================================================================

`ResNet(): deep module.` was successfully instantiated. Nbr.params: 11337817 .... [OK]
Optimizer `['dampening:0.0', 'lr:0.001', "lr_scheduler:{'gamma': 0.1, 'last_epoch': -1, 'min_lr': 1e-07, 'name': 'mystep', 'step_size': 40}", 'momentum:0.9', 'name:sgd', 'nesterov:True', 'weight_decay:1e-05']` was successfully instantiated .... [OK]
Learning scheduler `['gamma:0.1', 'last_epoch:-1', 'min_lr:1e-07', 'name:mystep', 'step_size:40']` was successfully instantiated .... [OK]

================================================================================
                                  START TRAINING
================================================================================

100%|█████████████████████████████████████████| 121/121 [00:11<00:00, 11.68it/s]
Tr.Ep  0: ACC: 0.3027, MAE: 1.3564, SOI_Y: 0.5413, SOI_PY: 0.7012, Loss: 1.5364, LR: ['1.00e-03'], t: 0.0000, time:0:00:12.233162
100%|█████████████████████████████████████████| 109/109 [00:03<00:00, 31.98it/s]
Vl.Ep  0: ACC: 0.4404, MAE: 1.0734, SOI_Y: 0.6193, SOI_PY: 0.7638, Loss: 1.3830, t:0.0000, time:0:00:03.899129
Plotting stats ...
  7%|██▊                                        | 8/121 [00:01<00:18,  6.12it/s]^C

'''

**Comment by vishwa15-lab** [comment]
@sbelharbi Thank you. I was using conda virtual environment and there was version mismatch of some libraries. I installed exact version and fixed the problem. Thanks for your time.
